### ISSUE TITLE
error when training

### ISSUE THREAD

**Issue by chenj02** [JiaweiXu8/Grid4D#2]
there are some errors when training
```

root@6555db9f29dc:/data/chenj02/3DGS/code/Grid4D# python train.py -s /data/chenj02/3DGS/data_hypernerf/slice-banana -m /data/chenj02/3DGS/train_model_grid4d/hypernerf --conf arguments/hypernerf/interp_slice-banana.py
Detected CUDA files, patching ldflags
Emitting ninja build file ./tmp_build/build.ninja...
Building extension module _hash_encoder...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=_hash_encoder -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /opt/conda/lib/python3.10/site-packages/torch/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 -std=c++14 -allow-unsupported-compiler -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -c /data/chenj02/3DGS/code/Grid4D/hashencoder/src/hashencoder.cu -o hashencoder.cuda.o 
FAILED: hashencoder.cuda.o 
/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=_hash_encoder -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /opt/conda/lib/python3.10/site-packages/torch/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 -std=c++14 -allow-unsupported-compiler -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -c /data/chenj02/3DGS/code/Grid4D/hashencoder/src/hashencoder.cu -o hashencoder.cuda.o 
In file included from /opt/conda/lib/python3.10/site-packages/torch/include/c10/util/string_view.h:4,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/c10/util/StringUtil.h:6,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/c10/util/Exception.h:5,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/Generator.h:11,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/Context.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/cuda/CUDAContext.h:18,
                 from /data/chenj02/3DGS/code/Grid4D/hashencoder/src/hashencoder.cu:5:
/opt/conda/lib/python3.10/site-packages/torch/include/c10/util/C++17.h:27:2: error: #error You need C++17 to compile PyTorch
   27 | #error You need C++17 to compile PyTorch
      |  ^~~~~
In file included from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /data/chenj02/3DGS/code/Grid4D/hashencoder/src/hashencoder.cu:6:
/opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4:2: error: #error C++17 or later compatible compiler is required to use PyTorch.
    4 | #error C++17 or later compatible compiler is required to use PyTorch.
      |  ^~~~~
In file included from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:4,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:9,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /data/chenj02/3DGS/code/Grid4D/hashencoder/src/hashencoder.cu:6:
/opt/conda/lib/python3.10/site-packages/torch/include/ATen/ATen.h:4:2: error: #error C++17 or later compatible compiler is required to use ATen.
    4 | #error C++17 or later compatible compiler is required to use ATen.
      |  ^~~~~
[2/3] c++ -MMD -MF bindings.o.d -DTORCH_EXTENSION_NAME=_hash_encoder -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /opt/conda/lib/python3.10/site-packages/torch/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -std=c++14 -c /data/chenj02/3DGS/code/Grid4D/hashencoder/src/bindings.cpp -o bindings.o 
FAILED: bindings.o 
c++ -MMD -MF bindings.o.d -DTORCH_EXTENSION_NAME=_hash_encoder -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /opt/conda/lib/python3.10/site-packages/torch/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -std=c++14 -c /data/chenj02/3DGS/code/Grid4D/hashencoder/src/bindings.cpp -o bindings.o 
In file included from /opt/conda/lib/python3.10/site-packages/torch/include/torch/extension.h:5,
                 from /data/chenj02/3DGS/code/Grid4D/hashencoder/src/bindings.cpp:1:
/opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4:2: error: #error C++17 or later compatible compiler is required to use PyTorch.
    4 | #error C++17 or later compatible compiler is required to use PyTorch.
      |  ^~~~~
In file included from /opt/conda/lib/python3.10/site-packages/torch/include/c10/util/string_view.h:4,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/c10/util/StringUtil.h:6,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/c10/util/Exception.h:5,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/c10/core/Device.h:5,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/TensorBody.h:11,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/Tensor.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/Tensor.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/extension.h:5,
                 from /data/chenj02/3DGS/code/Grid4D/hashencoder/src/bindings.cpp:1:
/opt/conda/lib/python3.10/site-packages/torch/include/c10/util/C++17.h:27:2: error: #error You need C++17 to compile PyTorch
   27 | #error You need C++17 to compile PyTorch
      |  ^~~~~
In file included from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:4,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:9,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/extension.h:5,
                 from /data/chenj02/3DGS/code/Grid4D/hashencoder/src/bindings.cpp:1:
/opt/conda/lib/python3.10/site-packages/torch/include/ATen/ATen.h:4:2: error: #error C++17 or later compatible compiler is required to use ATen.
    4 | #error C++17 or later compatible compiler is required to use ATen.
      |  ^~~~~
In file included from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/ivalue.h:1499,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/List_inl.h:4,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/List.h:490,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/IListRef_inl.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/IListRef.h:632,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/WrapDimUtils.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/TensorNames.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/NamedTensorUtils.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/variable.h:11,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/extension.h:5,
                 from /data/chenj02/3DGS/code/Grid4D/hashencoder/src/bindings.cpp:1:
/opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/ivalue_inl.h: In lambda function:
/opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/ivalue_inl.h:1061:30: error: 'is_convertible_v' is not a member of 'std'; did you mean 'is_convertible'?
 1061 |         if constexpr (::std::is_convertible_v<typename c10::invoke_result_t<T &&, Future&>, IValueWithStorages>) {
      |                              ^~~~~~~~~~~~~~~~
      |                              is_convertible
/opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/ivalue_inl.h:1061:91: error: expected '(' before ',' token
 1061 |         if constexpr (::std::is_convertible_v<typename c10::invoke_result_t<T &&, Future&>, IValueWithStorages>) {
      |                                                                                           ^
      |                                                                                           (
/opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/ivalue_inl.h:1061:111: error: expected primary-expression before '>' token
 1061 |         if constexpr (::std::is_convertible_v<typename c10::invoke_result_t<T &&, Future&>, IValueWithStorages>) {
      |                                                                                                               ^
/opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/ivalue_inl.h:1061:112: error: expected primary-expression before ')' token
 1061 |         if constexpr (::std::is_convertible_v<typename c10::invoke_result_t<T &&, Future&>, IValueWithStorages>) {
      |                                                                                                                ^
In file included from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/boxing/KernelFunction_impl.h:1,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/boxing/KernelFunction.h:251,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/op_registration/op_registration.h:11,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/library.h:68,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/autograd_not_implemented_fallback.h:3,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:4,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /opt/conda/lib/python3.10/site-packages/torch/include/torch/extension.h:5,
                 from /data/chenj02/3DGS/code/Grid4D/hashencoder/src/bindings.cpp:1:
/opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/boxing/impl/boxing.h: In static member function 'static Result c10::impl::BoxedKernelWrapper<Result(Args ...), typename std::enable_if<((c10::guts::conjunction<c10::impl::can_box<Args>...>::value && c10::guts::conjunction<c10::guts::disjunction<c10::impl::has_ivalue_to<T, void>, std::is_same<void, ReturnType> >, c10::guts::negation<std::is_lvalue_reference<_Tp> > >::value) && (! c10::impl::is_tuple_of_mutable_tensor_refs<Result>::value)), void>::type>::call(const c10::BoxedKernel&, const c10::OperatorHandle&, c10::DispatchKeySet, Args ...)':
/opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/boxing/impl/boxing.h:229:25: error: 'is_same_v' is not a member of 'std'; did you mean 'is_same'?
  229 |     if constexpr (!std::is_same_v<void, Result>) {
      |                         ^~~~~~~~~
      |                         is_same
/opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/boxing/impl/boxing.h:229:35: error: expected primary-expression before 'void'
  229 |     if constexpr (!std::is_same_v<void, Result>) {
      |                                   ^~~~
/opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/boxing/impl/boxing.h:229:35: error: expected ')' before 'void'
  229 |     if constexpr (!std::is_same_v<void, Result>) {
      |                  ~                ^~~~
      |                                   )
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
    subprocess.run(
  File "/opt/conda/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/chenj02/3DGS/code/Grid4D/train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "/data/chenj02/3DGS/code/Grid4D/gaussian_renderer/__init__.py", line 15, in <module>
    from scene.gaussian_model import GaussianModel
  File "/data/chenj02/3DGS/code/Grid4D/scene/__init__.py", line 19, in <module>
    from scene.deform_model import DeformModel
  File "/data/chenj02/3DGS/code/Grid4D/scene/deform_model.py", line 4, in <module>
    from scene.network import DeformNetwork, Grid4D
  File "/data/chenj02/3DGS/code/Grid4D/scene/network.py", line 5, in <module>
    from hashencoder.hashgrid import HashEncoder
  File "/data/chenj02/3DGS/code/Grid4D/hashencoder/__init__.py", line 1, in <module>
    from .hashgrid import HashEncoder
  File "/data/chenj02/3DGS/code/Grid4D/hashencoder/hashgrid.py", line 12, in <module>
    from .backend import _backend
  File "/data/chenj02/3DGS/code/Grid4D/hashencoder/backend.py", line 10, in <module>
    _backend = load(name='_hash_encoder',
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension '_hash_encoder'
```
how to solve？

**Comment by seoha-kim** [comment]
Hello, I have the same issue.
Did you solve the problem? :( ,,

**Comment by seoha-kim** [comment]
I solved this problem using
export CUDA_HOME=/usr/local/cuda

I followed the below issue:
https://github.com/QianyiWu/objectsdf_plus/issues/13
